<?php
require 'vendor/autoload.php';
include('connection.php');
session_start();

if ($_SESSION["login"] != "true") {
    header("location:./login.php");
  }


$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);


$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Courier Management System');
$pdf->SetTitle('Monthly Shipment Report');
$pdf->SetSubject('Shipment Report for January 2024');
$pdf->SetKeywords('TCPDF, PDF, shipment, report, test, guide');


$pdf->SetHeaderData('', 0, 'Monthly Shipment Report', 'Generated by Courier Management System');


$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));


$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);


$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);


$pdf->AddPage();

$pdf->SetFont('helvetica', 'B', 12);


$pdf->Cell(0, 0, 'Monthly Shipment Report', 0, 1, 'C', 0, '', 0, false, 'M', 'M');


$pdf->Ln(10);


$pdf->SetFont('helvetica', '', 10);
$currentMonth = date('F');

$pdf->Write(0, "Report Details\n", '', 0, 'L', true, 0, false, false, 0);
$pdf->Write(0, "Date Range: $currentMonth 1, 2024 - $currentMonth 31, 2024\n", '', 0, 'L', true, 0, false, false, 0);
$pdf->Write(0, "Generated on: February 1, 2024\n", '', 0, 'L', true, 0, false, false, 0);
$pdf->Ln(10);

$pdf->Write(0, "Shipment Details\n", '', 0, 'L', true, 0, false, false, 0);
$pdf->Ln(2);

$tableHTML = '
<table border="1" cellpadding="3">
    <tr>
        <th>Courier Id</th>
        <th>Sender Name</th>
        <th>Sender Address</th>
        <th>Receiver Name</th>
        <th>Receiver Address</th>
        <th>Status</th>
        <th>Date & Time</th>
    </tr>';

$shipments = [];

    $query = "SELECT reference_id, sender_name, sender_address, recipient_name, recipient_address, status, date_created FROM courier";

    $result = mysqli_query($conn,$query);
    $rows = mysqli_num_rows($result);
   

    if ($result) {
        while ($row = mysqli_fetch_assoc($result)) {
            $shipments[] = $row;
        }
    }


foreach ($shipments as $shipment) {
    $tableHTML .= '<tr>';
    foreach ($shipment as $data) {
        $tableHTML .= '<td>' . $data . '</td>';
    }
    $tableHTML .= '</tr>';
}
$tableHTML .= '</table>';

$pdf->writeHTML($tableHTML, true, false, false, false, '');

$pdf->Ln(10);


$pending = 0;
$delivered = 0;
$in_transit = 0;

$sql_query = "SELECT status, COUNT(*) AS count FROM courier GROUP BY status";
$result = $conn->query($sql_query);

if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        switch ($row['status']) {
            case "pending":
                $pending = $row["count"];
                break;
            case "delivered":
                $delivered = $row["count"];
                break;
            case "in transit":
                $in_transit = $row["count"];
                break;
        }    
    }
}


$pdf->Write(0, "Summary\n", '', 0, 'L', true, 0, false, false, 0);
$pdf->Write(0, "Total Number of Shipments: $rows\n", '', 0, 'L', true, 0, false, false, 0);
$pdf->Write(0, "Delivered: $delivered\n", '', 0, 'L', true, 0, false, false, 0);
$pdf->Write(0, "In Transit: $in_transit\n", '', 0, 'L', true, 0, false, false, 0);
$pdf->Write(0, "Pending: $pending\n", '', 0, 'L', true, 0, false, false, 0);
$pdf->Ln(10);


$pdf->Write(0, "Prepared By\n", '', 0, 'L', true, 0, false, false, 0);
$pdf->Write(0, "Courier Management System\n", '', 0, 'L', true, 0, false, false, 0);
$pdf->Write(0, "Contact Information for Queries: support@couriercompany.com\n", '', 0, 'L', true, 0, false, false, 0);

$filePath = "C:/xampp/htdocs/E-Project/Report/Shipment_Report_".$currentMonth."_2024.pdf";
$pdf->Output($filePath, 'F');

header('location: download_report.php');
?>
